### ISSUE TITLE
Walls and other objects can make you invulnerable (works everywhere).

### ISSUE THREAD

**Issue by T4WER** [nmrih/source-game#1071]
Hello, sorry for my english, it doesn't matter. So. I learned about this lag or bug of the game from fans of a not very fair game and from my friends. I don’t know whether this flaw was posted here or not, but if it works, then i have to show it to you.
 Get to the point. This bug lies in the fact that when you get up close to the object and go out a little on the zombies, you do not receive damage from it. I think the problem is in the artificial intelligence of the zombie, you know better ..
 This is a very cheating bug and can greatly help in the passage of any maps. I respect this game and strive to make it even a little better. Thanks.
Game Version: 1.1.0.0
How to do it: find an object (wall, drawer, table, etc.), pull over to it and come to the edge a little, when the zombie grabs you, the damage will not pass. 
 As for the nmo_broadway2 map, you need to jump on the lock and just sit. I think this is just a variation of this bug.
Video: https://www.youtube.com/watch?v=qud-lVHMY0g

**Comment by Holycrapjimhox** [comment]
To be fair, this issue is not nearly as exploitable as you describe it to be. The biggest advantage it can bring to the players is stopping zombies from going through a chokepoint like a door or narrow passage. It can save the team in some sticky situations, but if you don't have enough melee or ammo (also dependent on map and difficulty) you won't be able to make it through. You only prevent zombies from flooding an area, and you always need a doorway or similar geometry. It may make some custom map's ending trivial if it consists of pure runner spam through a doorway, but that's a very situational use. Despite all of this, it's clearly an exploit, and if it can be fixed, it should be fixed. Thanks for the report.

Also, note that the exploit you showed on nmo_broadway2, standing on top of the lock, is not related to the issue you reported, that is simply called an exploitable "god spot". It's a spot where a player can stand where zombies can't attack them, regardless if it's caused by the zombies being dumb or the geometry being in their favor. Again, thanks for reporting this one too, it would make the first part of broadway2 pretty trivial to complete solo.
