### ISSUE TITLE
nmo_broadway2 The player dies in the train due to the explosion of the end.

### ISSUE THREAD

**Issue by marcodromero** [nmrih/source-game#1072]
In the end the player dies waiting inside the train to move due to the explosion of the end.
Suggestion: The train should start before the explosion or the interior should protect the players with a new trigger "trigger_noburn" (?

**Comment by Holycrapjimhox** [comment]
I don't consider this to be an issue. Broadway2 is special in the sense that it has two separate timers. The first 5 minute timer is the bomb, which forces the players to rush forward as fast as they can. The second timer is the extraction timer, which is completely independent of the bomb timer and it starts counting down as soon as the player unlocks either one of the two extractions by reaching the crashed helicopter. It is only dependent on how fast the players managed to progress through the map after using the radio.

Protecting players inside the train as the bomb goes off doesn't make much logical sense. The lady on the radio explicitly says that the players will die if they don't leave the city before the explosion, so we can infer that the bomb is powerful enough to wipe out most of the city. A small, thin and brittle train coach would not be able to withstand such destructive power.

Additionally, leaving the subjective gameplay logic aside, the train escape is the most trivial of the two. You literally need to go up the building, down the stairs and you're done. Creating a special entity that protects players from a very generous 5 minute death timer would make a brain-dead easy escape even more trivial.

If you are concerned about survivors lagging behind, there is absolutely no problem. The only thing that causes players to die in the train, is activating the escape late enough for the bomb to go off. As long as someone is fast enough to trigger the escape with enough time left to reach the extraction trigger on top of the tracks, then slower survivors still have a chance. If players can't even manage to activate the escape efficiently enough, then they need to play the map more times to learn in properly and move faster.

**Comment by Loboo** [comment]
The rescue would be more realistic if you take into consideration the time left for the detonation of the bomb. Why would we wait a minute on the train when the city is about to explode?
Players do not die when entering the helicopter of the basketball court when the bomb explodes. We are facing a realistic extraction and another that is not.

**Comment by Holycrapjimhox** [comment]
Players don't die when entering the helicopter because they are technically not alive anymore, they have been extracted. That's the difference between both escapes, you get to access the escape trigger at different times. Even though the train forces you to wait for that trigger, it's just an incredibly easy escape. Players almost always win the map that way, unless they are extremely slow, which the map clearly penalizes.

Also, the train waits a minute before leaving because if it didn't, the only player that would escape is the one that triggered its arrival, while other players would have no chance of getting there. If you still want to make this escape even easier, the most logical thing to do is add a player check, so that when every live player has entered the train, it should leave immediately. If slow players are taking too long, the player that rushed ahead would die if the train wouldn't move until all players get there, so the timer must still be present, if not, any player could sit at the initial player spawn and troll, blocking the escape for everyone.

However, I still think all this is unnecessary, the escape is trivial and by simply putting a minimum amount of effort in learning the map properly and knowing how to dodge zombies, players can consistently win the map via the train. In the dozens of times I've played the map online, I've seen players die once waiting for the train to get to the extraction trigger, and they were incredibly slow.

**Comment by felis-catus** [comment]
Closing.
