### ISSUE TITLE
Broadway2 Timer Broken

### ISSUE THREAD

**Issue by Valourants** [nmrih/source-game#1164]
The timer in broadway2 is potentially broken or the messages badly timed/misleading. The map always ends shortly after the 2 minutes left broadcast. 

Either, it's not actually counting those 2 minutes, and ending the map early. Or the timer works properly but it's broadcasting 2 minutes left at the wrong time and ending the map 20 seconds after etc. Also if it's announcing 2 minutes left for the nuke timer? and ending the map because extraction timer is up, then the message needs to specify that it's 2 minutes left until nuke drops or that there is 2 minutes left until evac leaves. 

As well if there is 2 minutes left until nuke drops, but 10 seconds until evac leaves? then the 2 minute announcement is not really important. no one needs to know something that will never happen because we already lost the map due to the evac timer running out. The messages should probably prioritize the timer that is lowest once both timers become active since the other time will be irrelevant. 

This happened on train extraction. 

It just needs to be more accurate.

**Comment by Holycrapjimhox** [comment]
The timer is not broken, Broadway 2 is a unique map because it has 2 separate timers. The first one is the one marked on the screen "5 minutes remaining until detonation" and it counts down each minute that passes. When it reaches 0, you have around 20 seconds before every player on the map is killed. The second timer is an escape timer exactly like any other map in the game.

The important thing to understand is that they are independent. The detonation timer always starts first and counts down normally. Then, once you go up to the rooftop and the cinematic ends, the escape timer begins counting down. You then have 2 minutes to reach the escape in the case of the helicopter for example. For example, if you take 1 minute to reach the helicopter, but the detonation timer had only 10 seconds remaining, you won't reach it in time and you'll die due to the explosion.

It can be confusing at first, but once you understand the mechanics, it's not a problem. Maybe an additional timer could be added so that the player knows how much time they have left before the escape vehicle leaves, but again, with a bit of practice this is not necessary. Most maps have strict timers when the extraction begins, the game teaches you to haul ass every time the escape vehicle arrives.

**Comment by AtheistNMRiH** [comment]
> Also if it's announcing 2 minutes left for the nuke timer? and ending the map because extraction timer is up, then the message needs to specify that it's 2 minutes left until nuke drops or that there is 2 minutes left until evac leaves.

Text was clarified in last update (1.11.2), it definitely says "X minutes remaining until detonation."

**Comment by felis-catus** [comment]
Assuming this is not a bug.
