### ISSUE TITLE
nms_arpley map improvements/issues

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#1178]
Found in public 1.11.4, but they've always been here

![20210226003337_1](https://user-images.githubusercontent.com/15934200/110229716-5e8c3680-7ec0-11eb-8b8b-3050187f5a75.jpg)
![20210306202452_1](https://user-images.githubusercontent.com/15934200/110229718-61872700-7ec0-11eb-8c43-7503565fe5c7.jpg)
![20210306204635_1](https://user-images.githubusercontent.com/15934200/110229719-621fbd80-7ec0-11eb-960f-3a6ddebbb0b3.jpg)
![20210306204707_1](https://user-images.githubusercontent.com/15934200/110229721-621fbd80-7ec0-11eb-9e89-7de4ee3d2cb2.jpg)
![20210306204852_1](https://user-images.githubusercontent.com/15934200/110229722-621fbd80-7ec0-11eb-9345-6d32060c00e1.jpg)
![20210306205711_1](https://user-images.githubusercontent.com/15934200/110229723-62b85400-7ec0-11eb-8076-1f6f1044800c.jpg)
![20210306205723_1](https://user-images.githubusercontent.com/15934200/110229724-62b85400-7ec0-11eb-95a0-c2e42a699c02.jpg)
![20210306205851_1](https://user-images.githubusercontent.com/15934200/110229725-6350ea80-7ec0-11eb-8186-383f58a9d021.jpg)

**Comment by AtheistNMRiH** [comment]
- props not having collision is intended, it's general practice on all maps, so you and zombies don't stuck in them (maybe gonna add it for tracks, since there is a smooth clip on them)
- zombie stuck is mainly ai and geometry issues (they don't like narrow spaces, but I can't do much about it here, requires changes in geometry, gonna try to disable collision on door frame, maybe could help a little)
- as for reducing safe zone and railings:
1) I didn't understand last one, if players are on railings it is still a safe zone, or you mean that they go through barricades and leave zone for some time?
2) if players can jump on railings, then zombies should be able too, because it is god spot, but I don't want to clip railings because as I understand it is intended that you can jump in the river, maybe you have another solution for that

**Comment by Winning117** [comment]
I think there should be a clip there then cause currently the player can just walk into it and see inside of the prop which is funky.

Maybe if I can come up with an easily reproducible version on a test map it'll be easier for felis to come up with a fix for AIs getting stuck.

1. Here's a [video](https://www.youtube.com/watch?v=-Ht0xVo1dKI) of what I mean. Since the outer path counts as the safe zone, the player can spam jump over the railing to abuse the zombie's pathing. The zone doesn't drain since they're still technically in the safe zone, but if the outside isn't the safe zone anymore then the zone will start to drain when they jump over the railing (currently it doesn't drain since they're still in the safe zone).
2. Yeah I agree that we shouldn't clip the railings. Is it too tall for zombies to hit the player without the nav_jump? Ideally they could still reach the player there but I don't know if there's a good solution for that. When I was playing solo I saw some runners on those railings and I wasn't even using the railings lmao

**Comment by Holycrapjimhox** [comment]
I suggest against adding more player clips on the rails or walkable spaces. Since players have to engage the zombies inside the bridge for maximum effectiveness, having player clips that can constantly block their movement would be annoying. Clips can even create uneven surfaces where a player can suddenly rise a few centimeters above their previous height, causing missed melee swings and shots. In fact, the rails have such a collision, which make melee combat inside the zone a bit frustrating. I prefer to have more fluid movement and player models clipping into the geometry than the opposite case.

**Comment by AtheistNMRiH** [comment]
- ok, got it about zone, I'll reduce it and test it out
- Is it too tall for zombies to hit the player without the nav_jump? yes, you can go a little further to river and zombies won't hit you (standart god spot mechanic), in general gameplay I didn't see players somehow abusing rails, it isn't so OP, and if zone will be reduced it will be even less efficient

**Comment by AtheistNMRiH** [comment]
after reducing zone, you can now just stand in the area near railings and zombies will completely ignore the zone (player is always more important than zone)
before reducing, if you are inside the zone they could begin to attack it, if there are many of them

**Comment by Winning117** [comment]
Ah damn, if they ignore the zone completely then that's not much of a fix either. If you lower the safezone so that the player has to be standing on the ground (or at least low enough so standing on the railing doesn't trigger it) will that help? That way players standing on the railing aren't in the safe zone anymore.

**Comment by AtheistNMRiH** [comment]
it will be the same as now — standing on rails will cause zombies to ignore zone and climb on railings, if I'll remove nav_jumps — you can harmless kill zombies and they still won't attack zone, now at least they can sometimes climb on railings and prevent you from sitting in one place
I might be wrong, just need to test which variant is less exploitable

**Comment by Winning117** [comment]
Seems like no matter what we do we'll be compromising in some way so it's probably best to leave the safezone the way it currently is ^.^

**Comment by AtheistNMRiH** [comment]
added collision to rails and table in r9071, also added experimental nav_jumps on these rails, so zombies can faster reach players on the other side, requires testing
![nms_arpley0000](https://user-images.githubusercontent.com/11333747/110334030-e60aae80-8054-11eb-93d3-3d6c79a42562.jpg)

**Comment by Winning117** [comment]
Confirmed that the rails are now fixed, much better! Players can still lose items inside of the battery holder and the trash bags.

Also it appears that the new nav_jumps are a little messy with those giant truss beams in the way
![Untitled](https://user-images.githubusercontent.com/15934200/110601474-d3b67080-8139-11eb-9e4c-6f2ee9e58b0b.png)

**Comment by AtheistNMRiH** [comment]
every nav_jump in all maps is messy, if there are many zombies trying to climb together
what do you mean by stuck? because they climbed, just pushed me and were staying on top of my head, if you meant this

**Comment by Winning117** [comment]
Standing in front of the whole railing is essentially a god spot. The zombies aren't able to attack me while standing on top of the railings. I can upload a video of it if you would like

**Comment by dysphie** [comment]
what's a godspot useful for if your zone still gets overrun

**Comment by Winning117** [comment]
It doesn't get overrun though because you're still in the safezone, makes it super easy to cheese

**Comment by AtheistNMRiH** [comment]
removed experimental nav_jumps in r9072, too much hate for them :'(

**Comment by Winning117** [comment]
Looks good (sorry I lost this notification deep within my emails)
