### ISSUE TITLE
[public-1.11.4] Scores don't reset after leaving practice mode

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1187]
Kills, deaths and respawn tokens remain set on a new round.

Repro:
- Get kills during warmup in casual mode
- Reset round
- Respawn tokens remain available

**Comment by felis-catus** [comment]
Renamed, the issue here is with scores not being reset after leaving practice mode, not regular round restarts. However there's a minor oversight with tokens getting reset on "round enter" state instead of "pre-round", as a result the previous token count is displayed on scoreboard before the match begins - this will be fixed.

**Comment by felis-catus** [comment]
Fixed in src-r5052.
