### ISSUE TITLE
[public-1.11.5] "Downloading map from workshop" screen goes away

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1220]
The "Downloading map from workshop" screen goes away after like 15 seconds and you get sent back to the home screen.
However the client continues downloading files in the background and reconnects to the server when done.
During this time you can interact with the UI which is pretty confusing

**Comment by dysphie** [comment]
I think it happens when you go past the 64 MB mark (which would previously reset the progress bar)

**Comment by felis-catus** [comment]
Haven't encountered this in the public build or during testing. Did you try escaping from the loading screen, or interact with the panel in any way? Workshop downloads can't be canceled from the API, hence the ability to exit was disabled. In fact, prior to 1.11.5 the dialog simply failed to show the progress due to programming error, and resulted in static display instead - no other functionality has been changed since then.

**Comment by dysphie** [comment]
> Did you try escaping from the loading screen, or interact with the panel in any way? 
Not intentionally no. The only thing I do is alt-tab sometimes.

**Comment by TheUnstableNutcase** [comment]
I've also experienced this bug. I didn't try pressing anything or interacting with the loading screen in anyway, it just happens by itself

**Comment by felis-catus** [comment]
It appears to occur when server has FastDL enabled in conjunction with Workshop, most likely a bug when transferring data from GameUI to our custom VGUI dialog.

**Comment by felis-catus** [comment]
Bumping up priority for 1.12 hotfix.

**Comment by felis-catus** [comment]
Fixed in src-r5698.
