### ISSUE TITLE
[public-1.12.0] nmo_anxiety appears "map differs from the server's" if you have downloaded the custom map of the workshop

### ISSUE THREAD

**Issue by MacReady82** [nmrih/source-game#1240]
The old custom anxiety map and the new anxiety map have the same name and cause a file conflict.
![20211101180707_1](https://user-images.githubusercontent.com/87544192/139743125-f2800fcb-19ac-4c53-ad98-76fc6135d5f8.jpg)

**Comment by Holycrapjimhox** [comment]
This is an issue with the WS entry, not the game itself. It's up to the uploader to change the name of the WS map to another one so that this issue is fixed.

In the meantime, you can fix your client by deleting the original version from your files. The original WS entry has been hidden, so I don't know if you can still unsubscribe, so, try deleting the files directly. Go to: **C:\Program Files (x86)\Steam\steamapps\workshop**,  search for any files named "anxiety" and delete them.
