### ISSUE TITLE
[Feature Request] Better shove damage with firearms

### ISSUE THREAD

**Issue by Acrilyk** [nmrih/source-game#1242]
I'd like the shove damage with firearms to be more customized somewhat, weapons like the Sako should deal some more damage with the shove compared to a pistol, for example the sako could deal as much damage as a baseball bat lightswing. Generally rifle stocks can do some serious damage

**Comment by dysphie** [comment]
This is bad because shoves can be chained and it would basically allow you to deal a ton of damage almost instantly with little stamina penalty. And if you tried to balance this by increasing the stamina cost you create another problem where your character becomes tired by simply trying to push zombies out of the way

**Comment by Acrilyk** [comment]
Maybe have it like the SKS with bayonet where there's a cooldown. If you're carrying a pistol/melee you should be more mobile and shove significantly faster than with a heavy rifle. I thought about this to mitigate those situations where you must only kill like one or two zeds but have no melee. Maybe not deal too much damage( to prevent that chaining like you said), but not so little(1 dmg)

**Comment by felis-catus** [comment]
Closing as rejected for now, you may discuss it further in this thread.
