### ISSUE TITLE
[Feature Request] Level transition

### ISSUE THREAD

**Issue by Acrilyk** [nmrih/source-game#1278]
Level transition from HL2 would be great to have. It could result in longer maps, without the tradeoff of less detail (because of engine limitations).

**Comment by felis-catus** [comment]
Partially implemented in 1.13.2:
- Added beta version of level transition for developers, it's disabled by default, and server admins may toggle it with cvar "sv_level_transition"

Closing this since the initial implementation is done, create new issues for bugs and feature requests relating to level transition.
