### ISSUE TITLE
[public-1.12.3] My friend found problem with runners npc_nmrih_runnerzombie

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1352]
When zombie on trigger get BecomeCrawler: run -> crawl -> run
Current loop never end, so maybe bug with AI for zombie, need check more on other zombies too.

There map he make for test zombie:
[runner_crawler.zip](https://github.com/nmrih/source-game/files/9796015/runner_crawler.zip)

**Comment by felis-catus** [comment]
This was fixed in src-r6466.

**Comment by AtheistNMRiH** [comment]
it seems not fixed in r9847
![nmo_ravenholm_v30002](https://user-images.githubusercontent.com/11333747/227753282-49cbd332-ca55-456f-972f-a82a84f6cc5a.jpg)
![nmo_ravenholm_v30003](https://user-images.githubusercontent.com/11333747/227753283-fe950ed8-fafc-4757-b369-440f127fa509.jpg)
![nmo_ravenholm_v30005](https://user-images.githubusercontent.com/11333747/227753284-cb00592f-cf36-4b39-8e08-66158051c04b.jpg)
![nmo_ravenholm_v30006](https://user-images.githubusercontent.com/11333747/227753285-85ba7802-89d5-4449-9e38-76e79ca0b5b5.jpg)
![nmo_ravenholm_v30007](https://user-images.githubusercontent.com/11333747/227753287-f285428d-3916-48f9-8618-1975569eae9b.jpg)
![nmo_ravenholm_v30008](https://user-images.githubusercontent.com/11333747/227753288-2d147e20-b129-4360-a7f2-9f6d4ae2d051.jpg)
![nmo_ravenholm_v30009](https://user-images.githubusercontent.com/11333747/227753289-ef6ff7dd-a848-482c-9aba-3bd5d0c59766.jpg)
