### ISSUE TITLE
[public-1.13.0] stuck area in nmo_fema

### ISSUE THREAD

**Issue by Dayonn-dayonn** [nmrih/source-game#1366]
At nmo_fema, near where the rock was destroyed by TNT and jumped down to the pond, I get stuck.

At the spot between the rock and the wall, I use a dash-crouch-jump (since in previous versions I could ride the rock) to jump up.
I am on the rock. And if I stand up I will be stuck.

![20221118231710_1](https://user-images.githubusercontent.com/37202119/202734594-e45ac5d6-216b-42fd-8446-01c52510b373.jpg)

I tried to jump on a rock to get around to avoid a horde of zombies and got stuck. lol
There may be other places where players are stuck in contact with rocks and walls at the same time.

**Comment by AtheistNMRiH** [comment]
similar to #527 
I think that bug can happen pretty rare? because I've jumped few times like this and still could get out of stuck, but if I come very close to wall I can stuck forever, but only if I intenionally want to do it, I don't see a place for that bug in normal gameplay

as a soultion I need to clip eeevery displacement wall in fema, sounds very unnecessary

**Comment by Dayonn-dayonn** [comment]
At the time of finding I was soloing on an official nightmare server.
I was cornered in a corner and would have died even had I not been stuck. For those reasons, I agree that fixing this stack would not affect gameplay.

Also, upon checking, I could not find any other areas in the cave that might be a problem.
You may close this issue.

**Comment by felis-catus** [comment]
Closed by request.
