### ISSUE TITLE
[public-1.13.3] Zombies behave differently since last update.

### ISSUE THREAD

**Issue by Jeff-FD3S** [nmrih/source-game#1448]
zombies seem to prioritize players or breakeable objects over players that are below them, ex:ladders or lower ground level, as you can see in the demo i attached, in this cheese/godspot in nmo_saw(runners only) zombies used to stay with the player doing the bug, but that no longer is the case, they will go to the gate and when that is destroyed they will attack players near the elevator, only some zombies will stay with the players and they will be unpredictable as you can see.
hopefully this can be fixed, thank you for reading.

https://discord.com/channels/1031559086124322866/1078917681337602058/1148093588236943490

**Comment by felis-catus** [comment]
Merging with #1475.

**Comment by felis-catus** [comment]
Reopening, this is a separate behavior issue.

**Comment by felis-catus** [comment]
Speculative fix committed in src-r7665. Haven't got a chance to test it yet. 
(+ OP has a dead link, repro is vague)

**Comment by felis-catus** [comment]
Closing as resolved.

**Comment by DabPenBen** [comment]
I think I need more time to look at the ai to confirm, the aggro seems fixed but there's something seriously off about the zeds now they seem a little more twitchy and their idle wandering pathing seems to update frequently meaning they mostly stand still if they're not aggroed on someone rather than running around randomly wandering. When zombies are running at players sometimes they do their standing idle look left and right animation while running but that doesn't seem to cause issues but thought it was worth mentioning.
