### ISSUE TITLE
[Feature Request] func_precipitation FGD Update & func_precipitation_blocker Addition

### ISSUE THREAD

**Issue by BigHatMarley** [nmrih/source-game#1541]
Hello NMRIH Devs, once again I am making a humble request.

I have been playing with the Hammer editor and doing some fun business with custom mapping, as well as updating some ports from other source titles (primarily optimisation, a thing many neglect!)

I have been working on a map that featured large swathes of func_precipitation, as rain is a heavily used element within the stage. The offered options by default in Hammer only cover the original set, values 0 to 3 in Precipitation Type.

This covers rain, snow and ash (though reading VDC, may be errors graphically. Not an issue here though, but good to note that it says you may patch it.) These effects, when used in such large spanning manners cause immense rendering overhead and completely tanks performance when not properly culled with visleaves (which can be almost impossible in open map configurations!)

Therefore, I decided to experiment with the other values you can set within func_precipitation, and it turns out Precipitation Type : 4 - 7 worked completely fine for me, which is the Particle Rain, Particle Ash and Particle Snow introduced in the Left 4 Dead engine branch onwards. 

The only catch with this is that it passes through surfaces, as long as someone is within the func_precipitation brush volume. That's where func_precipitation_blocker would come in, and tell the system to ignore it when you're inside one. As of when I'm posting this, trying to use a non-FGD func_precipitation_blocker within the game simply returns an error in console and has no effect on the present weather.

So! I don't know how easy, or if it's even possible, for you guys to add func_precipitation_blocker to the game. If you can, mappers can use particle driven weather on func_precipitation without too much concern, which has proven to perform a far cry better than the original types in certain scenarios, as well as looking quite good while it's in use.

Even if you cannot add the requested entity, I'm sure I can still find use for the Precipitation Types without too much issue. It would be better if more can utilise it however!

Updating the FGD file to easily display the available Precipitation Types would only be a few values, which would be good for ease of use, but can be set either way with SmartEdit turned off.

Thanks for your time, and have a good rest of your day!

Links to appropriate VDC pages :
https://developer.valvesoftware.com/wiki/Func_precipitation
https://developer.valvesoftware.com/wiki/Func_precipitation_blocker

Screenshot of effect ingame, and console error :
![ConsoleError](https://github.com/user-attachments/assets/947b2931-fd96-4107-be4d-3b2b8b3f83a4)
![ParticleRainIndoors](https://github.com/user-attachments/assets/f3fc5fba-4b45-4f04-a29f-37e4c544afb9)

**Comment by felis-catus** [comment]
Thank you for an excellent post! 

`func_precipitation_blocker` will be added in 1.14.1, however, it's a custom implementation, so it may behave differently in comparison to L4D. With particle rain, you essentially have a "rainbox" attached to you, so culling open areas isn't going to work out - therefore its behavior is simple, "if view is within brush, pause emission", at least it'll work with blocking interiors as you described. It's worth checking out at some point how (or if) L4D does this, since it's a difficult problem to solve.

Default rain doesn't have this problem since its particles are placed in the world, so we can cull those within bounds.

Re: FGD entries, those are already included in `nmrih.fgd`. Do you have your own copy? You can also check your config, `nmrih.fgd` should be the only game config file, since it includes base FGDs for you. Having both explicitly included may cause them to stomp each other.

Closing as completed.

_(Added in src-r7773 & src-r7774)_

**Comment by BigHatMarley** [comment]
Just to comment on the FGD thing, I read what ones are being referenced by Hammer++, and it's only the default one for NMRIH. Opening it with Notepad++ and manually searching for func_precipitation indeed reveals the correct options are already present!

A strange occurrence indeed, but the particle rain options are present. So I'll probably just have to clean up my install and it'll probably correct itself. Nonetheless, it was worth the mention just in case.

Good luck with the rest of the updates, and good night.
