### ISSUE TITLE
Supply Crate Invincibility.

### ISSUE THREAD

**Issue by suprtommyman** [nmrih/source-game#378]
When walking through a supply crate, and standing in it, zombies will also walk in but will not attack you.
Tested on public servers, and is easily exploited.
(There might be a topic on this, but I searched key words and I didn't see a topic. Excuse me for not noticing should there be an existing topic on this bug)

**Comment by Fersigal** [comment]
Related to Med crates invulnerability, because they interact as prop_physics, i'd figure the damage retracts first to the supply drop instead of the player, this is extremely exploitable on maps such as nmo_shelter and nmo_suzhou as of the new patch and people will abuse it to gain an advantage over the zombies. This makes this system extremely unfair for other players as they're not in the same situation and allows players to cheat, also used for supply crates, but medcrates are more problematic as they are often used to clear out shamblers.

I'd figure this bug is hard to fix, since reenabling the collisions won't fix the problem necessarily.

**Comment by Bubka3** [comment]
#847 has more details but we will track it here.

```
Steps to reproduce:

Find
a) Supply drop (item_inventory_box)
b) Safe zone repair box (nmrih_safezone_supply)
c) Health station (nmrih_health_station)
Stand inside it
Zombies will get close but never attack you
```

**Comment by felis-catus** [comment]
Fixed in src-r4328.

**Comment by Winning117** [comment]
Confirmed fixed in src-r4367/dev-r8764, needs to be closed.
