### ISSUE TITLE
Survival Mode UI disappears

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#531]
Posting this as a reminder to essbuh:

On an uncommon basis the Zone HUD elements in Survival Mode disappear from a random number of the players on a server. Some players can't see the Zone Health info at all, while others can.

![2014-02-08_00002](https://f.cloud.github.com/assets/3606650/2118381/ff80d982-9102-11e3-93f6-765667660ca2.jpg)

This seems to be more common on Linux servers, haven't discovered the issue on our Windows SVN server

**Comment by Fersigal** [comment]
#705 Related

**Comment by Fersigal** [comment]
Mainly happens when a map has more than 3 zones, this is when the UI mostly disappears for survivors. I have not seen this happen on any other occasion other than when a survival map has more than 3 zones for a given survival map. It happens totally random and one round it might show 3 rounds, another round it might show 2, another it might show 1 and another time it might not show anything at all. Even the compass shows sometimes random zones and sometimes it might not even show a single one.

**Comment by yomox9** [comment]
I experienced this issue yesterday in Windows server/client. version1.09.7. There are plugins.
![20180213214400_1](https://user-images.githubusercontent.com/14893069/36176256-5b4dd1f8-1155-11e8-90e0-32c652e46844.jpg)
![20180213220712_1](https://user-images.githubusercontent.com/14893069/36176262-5ec50888-1155-11e8-8ef7-ad3a11efc49c.jpg)

server log
Ignoring unreasonable position (-1946.424561,-69.979706,-16401.037109)
from vphysics! (entity item_ammo_box)
Ignoring unreasonable position (-1945.489136,-70.538780,-22765.238281)
from vphysics! (entity item_ammo_box)
Ignoring unreasonable position (-1946.710083,-71.989868,-29102.222656)
from vphysics! (entity item_ammo_box)
Ignoring unreasonable position (-1946.924683,-69.747231,-35422.593750)
from vphysics! (entity item_ammo_box)
Ignoring unreasonable position (-1946.586548,-69.727791,-41782.566406)
from vphysics! (entity item_ammo_box)
Ignoring unreasonable position (-1946.985596,-70.915657,-48150.707031)
from vphysics! (entity item_ammo_box)
Ignoring unreasonable position (-1945.474976,-71.241005,-54484.558594)
from vphysics! (entity item_ammo_box)
Ignoring unreasonable position (-1947.693604,-70.208031,-60825.703125)
from vphysics! (entity item_ammo_box)
Ignoring unreasonable position (-1946.103638,-72.003799,-67178.531250)
from vphysics! (entity item_ammo_box)
Ignoring unreasonable position (-1946.932983,-69.887215,-73531.320313)
from vphysics! (entity item_ammo_box)
Ignoring unreasonable position (-1946.354492,-71.321770,-79856.039063)
from vphysics! (entity item_ammo_box)
Ignoring unreasonable position (-1946.852661,-69.964348,-86224.093750)
from vphysics! (entity item_ammo_box)
Ignoring unreasonable position (-1946.338257,-72.156242,-92543.257813)
from vphysics! (entity item_ammo_box)
Ignoring unreasonable position (-1947.688110,-70.201126,-98889.835938)
from vphysics! (entity item_ammo_box)
Ignoring unreasonable position
(-1945.387207,-70.839279,-105248.039063) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.744995,-71.775238,-111564.546875) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1946.270630,-70.227882,-117881.117188) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1945.461670,-71.325050,-124283.882813) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.153687,-70.231369,-130626.304688) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.789551,-70.811020,-136988.937500) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.081909,-70.819298,-143306.906250) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.766113,-71.309822,-149625.640625) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1946.809326,-69.850227,-155954.562500) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1946.005615,-70.025810,-162322.140625) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1945.991333,-71.848541,-168680.468750) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.449585,-71.968529,-175027.921875) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.298218,-70.113243,-181384.750000) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1945.488403,-71.008415,-187731.140625) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1946.649536,-71.746407,-194145.375000) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1945.704468,-70.279442,-200439.718750) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.820679,-70.420937,-206817.296875) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1946.050537,-69.884750,-213109.187500) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.428101,-70.802086,-219495.890625) from vphysics! (entity
item_ammo_box)
item_inventory_box at (0.000, 0.000, 0.000) has no model name!
Ignoring unreasonable position
(-1945.708862,-71.677650,-225898.156250) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1946.317993,-70.034622,-232254.656250) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.625854,-70.130653,-238595.000000) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1945.954712,-70.864510,-244948.500000) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1945.420410,-70.678368,-251289.734375) from vphysics! (entity
item_ammo_box)
L 02/13/2018 - 21:56:51:
"[JP]sharon<36><[U:1:104935343]><#SDK_Team_Unassigned>" disconnected
(reason "Disconnect by user.")
Dropped [JP]sharon from server (Disconnect by user.)
Ignoring unreasonable position
(-1946.044922,-71.361374,-257788.984375) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.509277,-72.037689,-263969.562500) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.579834,-71.807182,-270374.093750) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.175293,-70.667374,-276869.718750) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1945.773560,-70.146393,-283042.625000) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1945.438843,-70.614258,-289430.468750) from vphysics! (entity
item_ammo_box)
L 02/13/2018 - 21:57:19:
"[JP]yamayoshi00<3><[U:1:100720305]><#SDK_Team_Unassigned>"
disconnected (reason "Disconnect by user.")
Dropped [JP]yamayoshi00 from server (Disconnect by user.)
Ignoring unreasonable position
(-1945.599121,-71.438370,-295933.468750) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.019165,-70.959465,-302187.562500) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1946.851929,-70.110649,-308575.375000) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1946.424805,-69.755135,-314802.937500) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.502563,-70.202141,-321288.187500) from vphysics! (entity
item_ammo_box)
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname
in file materials/models/player/elis/ud/zombie01.vmt **←skin plugin's message**
VertexLitGeneric, VertexLitGeneric,
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname
in file materials/models/player/elis/ud/zombie01.vmt**←skin plugin's message**
VertexLitGeneric, (*VertexLitGeneric*),
Ignoring unreasonable position
(-1947.507568,-70.243126,-327609.906250) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1946.307251,-70.130272,-334013.968750) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1945.620728,-71.207314,-340520.843750) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1946.536621,-70.981377,-346726.656250) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1945.660889,-70.318146,-353127.281250) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1945.758545,-71.182404,-359409.406250) from vphysics! (entity
item_ammo_box)
#Chat_Prefix [JP]Sasami: !endwave
L 02/13/2018 - 21:58:15:
"[JP]Sasami<17><[U:1:847977758]><#SDK_Team_Unassigned>" say "!endwave"
Ignoring unreasonable position
(-1947.168213,-70.969109,-365972.281250) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1946.382202,-70.832321,-372132.843750) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.502563,-71.845543,-378607.968750) from vphysics! (entity
item_ammo_box)
Ignoring unreasonable position
(-1947.571167,-70.763535,-384863.156250) from vphysics! (entity
item_ammo_box)
#Chat_Prefix [JP]ymox9_saltydog: 全ゾーンの％が見えない・・
L 02/13/2018 - 21:58:33:
"[JP]ymox9_saltydog<34><[U:1:101315772]><#SDK_Team_Unassigned>" say
"全ゾーンの％が見えない・・"  **←"I can't see all zones %..."**

**Comment by felis-catus** [comment]
Fix attempted in code commits r4310 & r4312, needs further testing.

**Comment by Winning117** [comment]
Tested map in src-r4367/dev-r8759 for multiple waves when it would disappear before. I believe the issue is fixed.
