### ISSUE TITLE
Missing Material Effect when submerged in water

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#646]
In 1.09 there's the chance you'll encounter a missing material texture on your screen if you go underwater. We haven't found a reliable process to replicate it exactly, but it seems to occur with a combination of having mid to low health whilst being infected?

![2014-10-27_00001](https://cloud.githubusercontent.com/assets/3606650/4818991/46b95efc-5efb-11e4-81c6-51b6de228aa7.jpg)

**Comment by Fersigal** [comment]
This works on almost any source game as far as i can recall and it has to do with playing on HDR mainly, since i have never but ever encountered this issue on playing with LDR. It mainly happens when playing different maps with different water textures on them.

**Comment by DDysphie** [comment]
>since i have never but ever encountered this issue on playing with LDR
I just encountered this issue while playing with LDR, seems unrelated. It's looking for "material 1" whatever that means:

![Uploading 20180629104437_1.jpg…]()

**Comment by Dysphie** [comment]
Check the possibility of this being caused by `env_fog_controller`s trying to apply volumetric fog for the water. Can't say for sure but I often see `No such variable "$fogenable" for material "nature/water_name"` followed by the game searching for material `1` or `0` for underwater textures.

**Comment by Dysphie** [comment]
Okay so this is a hilarious method but I can confirm it works. Whatever the actual bug is, game will **always** look for material "1". So simply adding a texture named `1.vmt` and with `$nodraw 1` to the materials folder 'fixes' this issue. Just for the sake of testing, I made it display "MISSING TEXTURE" instead of a fully transparent material:

![20180921122933_1](https://user-images.githubusercontent.com/11559683/45890839-4c72b800-bd9a-11e8-864f-9e5b5137d29d.jpg)

**Comment by dysphie** [comment]
"fixed" (read above hack) in svn-8920

**Comment by felis-catus** [comment]
Dysphie's hack is shipped with 1.11, welcome to the next level.
