### ISSUE TITLE
[1.09.5] Throwing sledgehammers and fubars won't hit zombies

### ISSUE THREAD

**Issue by x5566asd** [nmrih/source-game#760]
Title, If you throw a sledgehammer or a fubar toward zombie, it will go through and hit the ground.
I know it must be a rebalancing due to throwing these two was too OP 

bonus:
![2015-09-29_00001](https://cloud.githubusercontent.com/assets/11902227/10164902/c7b58548-66ee-11e5-82c7-00c5c6943e98.jpg)

Should I even consider it as an issue?
Just aim down and perform a SKS suicide. It is not like a bug but it just too funny.

**Comment by X-rock-X** [comment]
Not a bug, I reduced the amount of throwforce on both weapons due to the fact that they are heavy weaponry and it fixed a certain issue with them too. I think I'll disable throwing on them all along in the end, still making decisions.

About the suicide, yeah I was aware but I can't fix it on my end. I'm thinking we can just make the camera fixed to one position when suiciding, unmovable by the player. Like how it is with barricading.
