### ISSUE TITLE
nms_isolated zombies number in each wave

### ISSUE THREAD

**Issue by TeXnoFile** [nmrih/source-game#764]
Version: 1.9.5 (since 1.9.4)

The number of zombies in each wave on nms_isolated is extremely low. The map is just plain boring. I did not see any note about lowering the number of Z´s in changelogs what-so-ever.

![2015-09-28_00001](https://cloud.githubusercontent.com/assets/12586797/10262650/eb887904-69d1-11e5-9b4e-bd39d8686e3a.jpg)
![2015-09-28_00002](https://cloud.githubusercontent.com/assets/12586797/10262651/eb90850e-69d1-11e5-965d-84e363a8d226.jpg)
![2015-09-28_00003](https://cloud.githubusercontent.com/assets/12586797/10262652/eb969782-69d1-11e5-9ac1-c7b01fdaf4ce.jpg)
![2015-09-28_00004](https://cloud.githubusercontent.com/assets/12586797/10262653/eb9a9c7e-69d1-11e5-862f-ed6ee62f4ecb.jpg)
![2015-09-28_00005](https://cloud.githubusercontent.com/assets/12586797/10262654/eba07c66-69d1-11e5-926b-a961b6c1fffa.jpg)
![2015-09-28_00006](https://cloud.githubusercontent.com/assets/12586797/10262655/eba46d4e-69d1-11e5-8f85-a9e10424eab1.jpg)
![2015-09-28_00007](https://cloud.githubusercontent.com/assets/12586797/10262656/eba73862-69d1-11e5-9c18-d74e618b18e3.jpg)
![2015-09-28_00008](https://cloud.githubusercontent.com/assets/12586797/10262657/ebac6e90-69d1-11e5-9d95-c9d4f1844cbe.jpg)

**Comment by lousaffire** [comment]
Zombie count needs raising then, any suggestions for number?

Sent from Outlook




On Sat, Oct 3, 2015 at 4:25 AM -0700, "TeXnoFile" <notifications@github.com> wrote:
Version: 1.9.5 (since 1.9.4)

The number of zombies in each wave on nms_isolated is extremely low. The map is just plain boring. I did not see any note about this in changelogs what-so-ever.

![2015-09-28_00001](https://cloud.githubusercontent.com/assets/12586797/10262650/eb887904-69d1-11e5-9b4e-bd39d8686e3a.jpg)
![2015-09-28_00002](https://cloud.githubusercontent.com/assets/12586797/10262651/eb90850e-69d1-11e5-965d-84e363a8d226.jpg)
![2015-09-28_00003](https://cloud.githubusercontent.com/assets/12586797/10262652/eb969782-69d1-11e5-9ac1-c7b01fdaf4ce.jpg)
![2015-09-28_00004](https://cloud.githubusercontent.com/assets/12586797/10262653/eb9a9c7e-69d1-11e5-862f-ed6ee62f4ecb.jpg)
![2015-09-28_00005](https://cloud.githubusercontent.com/assets/12586797/10262654/eba07c66-69d1-11e5-926b-a961b6c1fffa.jpg)
![2015-09-28_00006](https://cloud.githubusercontent.com/assets/12586797/10262655/eba46d4e-69d1-11e5-8f85-a9e10424eab1.jpg)
![2015-09-28_00007](https://cloud.githubusercontent.com/assets/12586797/10262656/eba73862-69d1-11e5-9c18-d74e618b18e3.jpg)
![2015-09-28_00008](https://cloud.githubusercontent.com/assets/12586797/10262657/ebac6e90-69d1-11e5-9d95-c9d4f1844cbe.jpg)









---
Reply to this email directly or view it on GitHub:
https://github.com/ZPSNMRiHIssues/nmrihissues/issues/764

**Comment by TeXnoFile** [comment]
It would be the best to keep the numbers as they were before this change. The map was perfect, waves were well balanced

**Comment by lousaffire** [comment]
fair play i can do that

Date: Sat, 3 Oct 2015 09:33:57 -0700

**Comment by TeXnoFile** [comment]
Amazing, glad to hear that lou. And when we are at that, maybe add few more of them in the last 3 waves..lets say. I love challenges ;)

**Comment by lousaffire** [comment]
Well thats a nice idea, but the overlord doesn't work like that it just increments every wave :s

Date: Sat, 3 Oct 2015 10:24:46 -0700

**Comment by TeXnoFile** [comment]
Oh i see. i thought you could manually adjust the number of Z´s in every wave. Well then ...just return it   to the way it was before :)

**Comment by Bubka3** [comment]
Fixed in svn build 8538
