### ISSUE TITLE
Junction Clipping Errors (Over 50 Errors)

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#782]
I made a compilation video of all the clipping errors I've found in the map nmo_junction

https://youtu.be/WvjiVZ74YZM

Also, some shopping carts are clipped while others aren't.. http://steamcommunity.com/sharedfiles/filedetails/?id=579444195

**Comment by ihatebreakcore** [comment]
![2015-12-19_00009](https://cloud.githubusercontent.com/assets/16367410/11916385/c3f84a28-a6a2-11e5-90ed-382d5bfb143e.jpg)
i think lots of clips should be fixed before more clips are added. many of the clips on junction seem very unnecessary or need to be fixed because they are not put in very well
![2015-12-19_00023](https://cloud.githubusercontent.com/assets/16367410/11916397/a8e1f27e-a6a3-11e5-83b1-6d5b6fad4f9f.jpg)
![2015-12-19_00018](https://cloud.githubusercontent.com/assets/16367410/11916400/bd89a82a-a6a3-11e5-9bd7-9a3b18abdcfe.jpg)

![2015-12-19_00010](https://cloud.githubusercontent.com/assets/16367410/11916388/0039631e-a6a3-11e5-985c-ca2c9c93a34a.jpg)
i also think some are dumb and disrupt gameplay 
![2015-12-19_00011](https://cloud.githubusercontent.com/assets/16367410/11916390/2bfe331c-a6a3-11e5-9ac7-d668d9bd140a.jpg)
![2015-12-19_00035](https://cloud.githubusercontent.com/assets/16367410/11916391/3caea3e0-a6a3-11e5-9e2e-29698eedd681.jpg)
![2015-12-19_00039](https://cloud.githubusercontent.com/assets/16367410/11916393/45fe93ec-a6a3-11e5-84f1-30eadd7295de.jpg)
i think clips should make sense and you shouldn't feel like there is an invisible wall everywhere you go. clip furniture that makes players invincible but don't just do it everywhere for sake of doing it everywhere. junction has very many inconsistencies with the objects clipped, one trashcan is clipped while another trash can isn't. are players even invincible on the trashcans? 
![2015-12-19_00012](https://cloud.githubusercontent.com/assets/16367410/11916401/c408e292-a6a3-11e5-9845-6def2e856a99.jpg)
![2015-12-19_00003](https://cloud.githubusercontent.com/assets/16367410/11916412/f5d1a4d0-a6a3-11e5-864f-27b3b1763752.jpg)
these are not clipped and players can still die on them, so why have transcans clipped?
![2015-12-19_00004](https://cloud.githubusercontent.com/assets/16367410/11916415/06e2c8d0-a6a4-11e5-95a8-93f5a6099364.jpg)
some of these are clipped while others are not clipped 
![2015-12-19_00020](https://cloud.githubusercontent.com/assets/16367410/11916419/206fd96e-a6a4-11e5-9228-87234b7a2f35.jpg)
![2015-12-19_00006](https://cloud.githubusercontent.com/assets/16367410/11916420/26da23ae-a6a4-11e5-8bcd-102b7d7babaf.jpg)
if they were clipped to keep people from jumping out of map, the places they jump to should be clipped, not the barrel. 




here are some little things i think should be fixed:
![2015-12-19_00029](https://cloud.githubusercontent.com/assets/16367410/11916408/d9351c9e-a6a3-11e5-801f-cdc6d1f698bf.jpg)
![2015-12-19_00030](https://cloud.githubusercontent.com/assets/16367410/11916409/ddf090a6-a6a3-11e5-8c41-b9a9e235ce2d.jpg)
![2015-12-19_00002](https://cloud.githubusercontent.com/assets/16367410/11916411/f10eab5a-a6a3-11e5-8ac1-aa81529e5bbc.jpg)
and also the corners of some cars can make it very awkward to dodge zombies 
![2015-12-19_00027](https://cloud.githubusercontent.com/assets/16367410/11916426/5cd11760-a6a4-11e5-85b6-6c0b0733cd79.jpg)
and why is this not clipped even though it is taller than the trashcans which are clipped? 
![2015-12-19_00043](https://cloud.githubusercontent.com/assets/16367410/11916429/72bc5af8-a6a4-11e5-8dcb-1b1004668b86.jpg)

junction is very frustrating for me at the moment, i think there are too many clips that are unnecessary and just disrupt the map.

**Comment by Winning117** [comment]
I agree completely :+1:

**Comment by Winning117** [comment]
Many of these issues are not completed, see https://www.youtube.com/watch?v=ivZb_m7cXYQ. Also, cubemaps are broken :p

**Comment by AtheistNMRiH** [comment]
most of the maps have tons props which haven't collision (trash bags, chairs and etc) this is done to prevent player and zombie from stucking every meter in tiny props (trash bag isn't really tiny, but it is easier to move when it hasn't collision)

**Comment by Fersigal** [comment]
Yes, it's aggravating for most players to bump into a prop that blocks their movement if it might even be a painting and it can fuck up the fluency of the map, this is exactly why we have those, but prop clips could easily be manipulated with the vertex tool, it's not like most mappers don't care, it's just a lot of work to get the correct edges done. (for prop clips and clips)

**Comment by Winning117** [comment]
I understand preventing players from getting stuck on small items but I think that phasing through barrels/fences/tvs/bikes is unacceptable.

**Comment by AtheistNMRiH** [comment]
well yeah, maybe some of them are useless (like fence near wall, zombies still can get you there), we should reconsider all props collision, but this isn't very important :stuck_out_tongue:

**Comment by AtheistNMRiH** [comment]
added collision for some props in r8791 but won't add to others, see why in my first comment, should be closed

**Comment by Winning117** [comment]
Confirmed fixed in src-r4405/dev-r8791.
