### ISSUE TITLE
SourceTV

### ISSUE THREAD

**Issue by Nikitos365** [nmrih/source-game#875]
For 8 players ?
engine error updateplayername with bogus slot 9

**Comment by AtheistNMRiH** [comment]
такое желательно на форумах писать, а не здесь

**Comment by Nikitos365** [comment]
Как-никак engine error

**Comment by AtheistNMRiH** [comment]
тогда все ок

**Comment by Bubka3** [comment]
Please do not post questions on the bug tracker. These questions belong on the troubleshooting forums section.

SourceTV will not work in nmrih due to the hardcoded 8 slot limitation. You might be able to change maxplayers to 7 and then waste a slot on SourceTV, but this will be not be supported by us,
