### ISSUE TITLE
nmo_chinatown objective issues

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#916]
1) Late objective triggers (saying to go through the sewers even though you're on the other side)
2) Objective objects aren't highlighted (welders/power cord)
3) Some objectives have multiple pings on the compass (gate lock and generator)
4) The player can be killed by the helicopter at the end of the map

https://www.youtube.com/watch?v=51C8_0PkgJ8
https://www.youtube.com/watch?v=8l3MwBhP158

Found in src-r4372/dev-r8765.

**Comment by AtheistNMRiH** [comment]
1) it is intentional, some of nay0r's map has it too, in this case trigger_once is located in laundry (you activate it right after breaking the boards) and has delay in ~10 seconds, tbh you won't notice that if you don't rush the map so won't fix
2) there are plenty of welders, I guess that they don't glow is intentional too, speaking about power cord, I believe it is clear enough to understand what you need to do there, but I can highlight it anyway if needed
3) there is always 1 white ping which leads you to nmrih_objective_boundary location, not a bug
4) I thought it was fixed, gonna look into that, thanks for observation

**Comment by Winning117** [comment]
Fixed by atheist
