### ISSUE TITLE
Suicide mutes voice chat

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#977]
Killing yourself causes voice chat to be muted (since it mutes all sound effects) but I think that you should still be able to hear voice chat because otherwise you miss out on what your teammates are saying to you. This was brought to my attention by Ryan so credits to him for finding this 👍

**Comment by Holycrapjimhox** [comment]
I don't think this is an issue. It doesn't look or feel like a proper suicide if you can still hear voice chat behind your black screen without any other sound effects. Besides, you only miss out like 3 seconds of dialog. If you change this, the suicide action stops looking like one.

**Comment by Ryan-nmrih** [comment]
I think muting the suicided player's voice chat is a major annoyance. At best, nobody says anything. Otherwise get ready to repeat yourself. The game doesn't hide the visual indicator that shows someone is speaking so you explicitly know that someone is talking and you're not hearing them.

I disagree that this would ruin the feel of a 'proper suicide'. Consider that the game has been missing the gunshot sounds from suiciding since forever and nobody has complained. Hearing your teammates off them self with a boom is much more visceral than voice chat deafness. Listening to your teammates astonished reactions adds to the suicide effect, in my opinion.

**Comment by felis-catus** [comment]
To accomplish this, we'll have to re-implement the existing "soundfade" logic as a custom sound mixer that filters all audio excluding the player voice. How this works is clunky at best (you'll have to force a client cvar change), I don't believe it's worth it for hearing ~3 seconds of missed chatter. Closing.
